apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: umer515k/node-app-backend
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://root:example@mongodb-service:27017/task-manager?authSource=admin"
        - name: ACCESS_TOKEN_SECRET
          value: "Rj2S?RVe9[]8-dCS6A**&b5Tsg$gwbg~Bd{*QTK"
